jacebrowning/memegen

- CHECKS
- memegen/routes/root.py
- requirements.txt
Added/Enable Dokku personal Paas support.
Please review, and merge it if you like it :)
> Dokku support

- memegen/app.py
- memegen/routes/__init__.py
- memegen/routes/overview.py
- memegen/templates/overview.html
- tests/test_routes_overview.py
If would be great if there was an overview page like [this](http://felixhummel.github.io/memegen/) but prettier.
> Overview Page

- Makefile
- README.md
- memegen/domain/text.py
- memegen/test/test_domain_text.py
> Allow hyphens and underscores to be escaped

- memegen/domain/text.py
- memegen/routes/image.py
Fixes #53 
-----
Reference: https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide
> Add server-side analytics to images

- .gitignore
- .pylintrc
- .travis.yml
- Makefile
- MemeGen.sublime-project
- README.md
- memegen/domain/text.py
- memegen/test/test_domain_text.py
- scent.py
- tests/test_routes_image.py
- tests/test_routes_links.py
- tests/test_routes_templates.py
Fixes #63
And updates project structure.
> Escape '?' and '!' in URLs

- memegen/domain/template.py
- memegen/test/test_domain_template.py
- memegen/test/test_services_template.py
240x240 because meme templates are tiny :(
> Add minimum image size

- memegen/domain/template.py
Ignore them and validate the URL at another time.
> Handle request timeout errors

- memegen/app.py
- memegen/routes/__init__.py
- memegen/routes/image.py
- memegen/routes/latest.py
- memegen/routes/root.py
- memegen/stores/image.py
- memegen/templates/latest.html
- memegen/templates/overview.html
- tests/test_routes_image.py
- tests/test_routes_latest.py
- tests/test_routes_root.py
> Add route to get the latest generated meme

- data/templates/jw/config.yml
Other images I considered:
- https://thevideotapeisdead.files.wordpress.com/2014/11/dark-and-brooding.jpg
- http://lovelace-media.imgix.net/uploads/914/fe6dd920-ee9d-0132-f0ca-0ed54733f8f5.jpeg
> Add meme: Probably Not a Good Idea

- memegen/app.py
- memegen/routes/__init__.py
- memegen/routes/_common.py
- memegen/routes/generator.py
- memegen/routes/root.py
- memegen/templates/generator.html
- tests/test_routes_generator.py
- tests/test_routes_root.py
Upon discovering this repo and realizing there was no "generator" page, I decided to take a shot at implementing one. This is a super rough cut but visually everything is there (e.g. lots of CSS to put into OOCSS, JS to remove from inline). Any thoughts/feedback on the visuals themself?
> Added generator page

- memegen/app.py
- memegen/routes/__init__.py
- memegen/routes/_common.py
- memegen/routes/aliases.py
- memegen/routes/image.py
- memegen/routes/root.py
- memegen/services/template.py
- memegen/test/test_services_template.py
- tests/test_routes_aliases.py
- tests/test_routes_root.py
This will be used to populate meme generation forms:
`curl http://memegen.link/aliases/\?name\=votestakes`
> Add aliases route

- app.json
- memegen/routes/_common.py
- memegen/routes/aliases.py
- memegen/routes/generator.py
- memegen/routes/image.py
- memegen/routes/latest.py
- memegen/routes/links.py
- memegen/routes/overview.py
- memegen/routes/root.py
- memegen/routes/templates.py
- memegen/templates/generator.html
- memegen/templates/image.html
- memegen/templates/latest.html
- memegen/templates/overview.html
> Add client-side tracking to image pages

- memegen/templates/latest.html
> Use javascript to reload latest meme

- .pylintrc
- data/templates/afraid/config.yml
- data/templates/ants/config.yml
- data/templates/ch/config.yml
- data/templates/fry/config.yml
- data/templates/kermit/config.yml
- data/templates/older/config.yml
- data/templates/sohappy/config.yml
- data/templates/xy/config.yml
- memegen/app.py
- memegen/domain/template.py
- memegen/routes/__init__.py
- memegen/routes/magic.py
- memegen/routes/root.py
- memegen/stores/template.py
- memegen/test/test_domain_template.py
- tests/test_routes_magic.py
- tests/test_routes_root.py
> Add 'magic' route to best-fit a meme

- Makefile
- scent.py
- scripts/generate_sample_images.py
- scripts/run_gui.py
> Add demo GUI to render live memes (with speech recognition)

- Makefile
- scripts/run_gui.py
This will likely be superseded by https://github.com/jacebrowning/memegen/pull/164.
> Add demo GUI to render live memes

- Makefile
- memegen/app.py
- memegen/extensions.py
- memegen/settings.py
- memegen/stores/image.py
- memegen/test/test_app.py
- requirements.txt
- scripts/generate_sample_images.py
> Add initial setup for Flask-SQLAlchemy

- memegen/routes/_common.py
- memegen/settings.py
https://i.imgur.com/M6bsIfk.png
:bomb: :boom:
> Fix mixed content warnings

- Makefile
- bin/post_compile
- manage.py
- memegen/app.py
- memegen/extensions.py
- memegen/settings.py
- memegen/stores/__init__.py
- memegen/test/test_app.py
- migrations/README
- migrations/alembic.ini
- migrations/env.py
- migrations/script.py.mako
- migrations/versions/7da56a4eb387_add_meme_and_words_tables.py
- requirements.txt
- tests/conftest.py
I use a similar setup for most projects at work. It has proven to be very useful, so I thought I'd share.
TODO:
> Database setup improvements

- memegen/routes/_parser.py
- memegen/routes/templates.py
- tests/test_routes_templates.py
> Add creation of new memes via POST

- README.md
Hi, I have added my meme plugin created for the Hain app to your doc : https://github.com/Metrakit/hain-plugin-meme
> Add Hain meme plugin

- README.md
- memegen/domain/text.py
Memes need hashtags. I added hashtags. I hope I did it right. :)
closes #72
> add hashtag as "~h" and slash as "~s"

- Makefile
- manage.py
- memegen/app.py
- memegen/routes/__init__.py
- memegen/routes/static.py
- requirements.txt
And remove WhiteNoise which should now be redundant with CloudFlare.
> Use the development server as the default

- memegen/domain/font.py
- memegen/domain/image.py
- memegen/services/image.py
- memegen/tests/test_domain_font.py
- scent.py
- tests/test_routes_image.py
> Hash alternate fonts/styles in filenames

- memegen/templates/base.html
- memegen/templates/index.html
- memegen/templates/latest.html
- memegen/templates/memegen.html
> Add common theming to all pages

- memegen/app.py
- memegen/routes/__init__.py
- memegen/routes/image.py
- memegen/routes/index.py
- memegen/routes/magic.py
- memegen/routes/static.py
- memegen/static/js/magic.js
- memegen/templates/latest.html
- memegen/templates/magic.html
- memegen/templates/memegen.html
> Add template for magic route

- memegen/app.py
- memegen/routes/__init__.py
- memegen/routes/custom.py
- memegen/templates/custom.html
- memegen/templates/index.html
- memegen/templates/layout.html
- memegen/templates/magic.html
> Add tab for custom memes

- memegen/app.py
- memegen/extensions.py
- requirements.txt
> Enable CORS

- memegen/routes/_cache.py
- memegen/routes/latest.py
- memegen/static/stylesheets/BootstrapXL.css
- memegen/static/stylesheets/stylesheet.css
- memegen/templates/index.html
- memegen/templates/latest.html
- memegen/templates/layout.html
- tests/test_images.py
> Use a specific number of columns for each screen size

- memegen/services/image.py
- tests/test_images.py
> Return an error for invalid extensions

- CHANGELOG.md
- memegen/__init__.py
- memegen/domain/text.py
- memegen/routes/api_templates.py
- memegen/tests/test_domain_text.py
- tests/test_api_root.py
- tests/test_api_templates.py
> Escape special characters in POST data

- .pylintrc
- CHANGELOG.md
- README.md
- manage.py
- memegen/__init__.py
- memegen/routes/_utils.py
- memegen/routes/api_aliases.py
- memegen/routes/api_templates.py
- memegen/routes/image.py
- memegen/settings.py
- memegen/stores/image.py
- memegen/tests/test_routes_utils.py
- scripts/generate_sample_images.py
- tests/test_api_root.py
- tests/test_images.py
> Add preview option to disable caching and analytics

- memegen/routes/_utils.py
- memegen/routes/image.py
- memegen/templates/image.html
- memegen/tests/test_routes_utils.py
> Enable Social Sharing of Memes via URL

- memegen/templates/image.html
> Add tags for Facebook

- app.json
- memegen/routes/_settings.py
- memegen/routes/_utils.py
- memegen/routes/api_fonts.py
- memegen/routes/api_root.py
- memegen/routes/api_templates.py
- memegen/routes/custom.py
- memegen/routes/index.py
- memegen/routes/latest.py
- memegen/routes/magic.py
- memegen/settings.py
- memegen/templates/base.html
- memegen/templates/image.html
- memegen/templates/layout.html
- memegen/tests/test_routes_utils.py
- tests/test_images_examples.py
> Load image settings from the environment

- CHANGELOG.md
- README.md
- memegen/__init__.py
- memegen/routes/api_magic.py
- memegen/routes/api_templates.py
- memegen/templates/custom.html
- memegen/templates/index.html
- memegen/templates/magic.html
- tests/test_api_root.py
- tests/test_api_templates.py
> Add copy buttons

- manage.py
- memegen/factory.py
- memegen/templates/base.html
- memegen/templates/layout.html
- memegen/tests/test_app.py
- memegen/tests/test_routes_utils.py
- scripts/generate_sample_images.py
- tests/conftest.py
> Bust the cache on CSS files

- memegen/routes/_utils.py
- memegen/tests/test_routes_utils.py
> Stop forcing SSL on external image URLs

- memegen/routes/_utils.py
- memegen/templates/image.html
- memegen/templates/share.html
> Fix the link to re-share memes

- memegen/static/js/default.js
- memegen/templates/custom.html
- memegen/templates/index.html
- memegen/templates/magic.html
- memegen/templates/share.html
> Show tooltip when links are copied

- memegen/templates/share.html
> Escape question marks in shared URLs

- CHANGELOG.md
- Makefile
- README.md
- memegen/__init__.py
- memegen/domain/template.py
- memegen/domain/text.py
- memegen/routes/image.py
- memegen/tests/test_domain_template.py
- memegen/tests/test_domain_text.py
- requirements/ci.txt
- scent.py
- tests/test_api_links.py
- tests/test_api_magic.py
- tests/test_api_root.py
- tests/test_api_templates.py
- tests/test_images.py
- tests/test_magic.py
> Switch to underscores as the default space character

- memegen/routes/api_templates.py
- memegen/static/javascript/index.js
- memegen/templates/index.html
Here is a small proposal about a way to easily get the masked URL when generating an image.
Please note that I'm not a CSS fan so the bootstrap part might require some changes.
> Add and use masked flag

- memegen/routes/image.py
- memegen/static/javascript/index.js
> Support options on masked images

- memegen/templates/custom.html
> Clear default values to make form fill easier

- memegen/static/javascript/index.js
- memegen/templates/custom.html
- memegen/templates/examples.html
- memegen/templates/index.html
- memegen/templates/share.html
> Consolidate share actions and include option to copy image URL

- CHANGELOG.md
- memegen/__init__.py
- memegen/routes/image.py
- tests/test_api_root.py
- tests/test_images.py
This will make it easier for sites to use this API as template picker.
> Disable watermark on blank images

- Pipfile
- Pipfile.lock
> Fix markdown dependencies

- memegen/routes/custom.py
- memegen/templates/custom.html
- memegen/templates/layout.html
- tests/test_custom.py
> Prefill the background image for custom memes

- .gitignore
- Makefile
- app/api/images.py
- app/api/templates.py
- app/models.py
- app/tests/test_apis.py
> Post templates

- .circleci/config.yml
- .verchew.ini
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
Closes https://github.com/jacebrowning/memegen/issues/492
> Add contributor docs

- .circleci/config.yml
- .gitignore
- Makefile
> Upload coverage results

- app/api/images.py
- app/tests/test_apis.py
> Reject long URLs

- .prettierrc.toml
- app/templates/base.html
- app/templates/index.html
- app/tests/test_views.py
- app/views.py
- poetry.lock
- pyproject.toml
- requirements.txt
> Render the README as HTML

- app/api/images.py
- app/helpers.py
- app/models.py
- app/types.py
- app/utils/images.py
- app/utils/meta.py
- app/utils/text.py
- poetry.lock
- pyproject.toml
> Use literal types for annotations

- README.md
> Add link to Zapier invite

- .deepsource.toml
- app/errors.py
- app/models.py
- app/tests/test_apis_shortcuts.py
- app/utils/images.py
Hey, I work at DeepSource, I ran DeepSource analysis on my fork of the repo and found [some improvements](https://deepsource.io/gh/withshubh/memegen/issues/?category=recommended) in the codebase, opening this PR so you can assess if our platform is right and helpful for you.
- Refactored unnecessary `else` / `elif` when `if` block has a `return` statement
- Removed unnecessary f-string
- Changed methods not using its bound instance to staticmethods
- Added .deepsource.toml
> fix issues affecting code quality

- app/api/clients.py
- app/api/memes.py
- app/api/templates.py
- scripts/check_deployment.py
> Document query params

- app/api/memes.py
- app/tests/test_apis_memes.py
> Reject invalid sizes

- app/views/memes.py
- app/views/shortcuts.py
- app/views/templates.py
> Document path parameters

- app/tests/test_views_memes.py
- app/tests/test_views_shortcuts.py
- app/views/memes.py
- templates/mmm/config.yml
> Return a 201 response after redirecting

- CHANGELOG.md
- app/models/template.py
- app/tests/test_docs.py
- app/tests/test_models_template.py
- app/tests/test_views_templates.py
- app/utils/images.py
- app/utils/urls.py
- app/views/memes.py
- app/views/templates.py
- pyproject.toml
> Add support for multiple overlays

- app/tests/test_views_memes.py
- app/tests/test_views_shortcuts.py
- app/tests/test_views_templates.py
- app/utils/urls.py
- app/views/memes.py
- app/views/templates.py
- templates/mmm/config.yml
This reverts commit 0928c32b0b65adcd93663ba82a9186974b4e4501.
> Only return a 201 status code after redirecting

- poetry.lock
- pyproject.toml
- requirements.txt
> Update Sanic to 21.12

- CONTRIBUTING.md
- Containerfile
Updating the Containerfile and the CONTRIBUTING markdown file.
Reference Issue https://github.com/jacebrowning/memegen/issues/670
> Updating Containerfile and the Contribuiter markdown file.

- .vscode/settings.json
- app/config.py
- app/main.py
- app/tests/test_docs.py
- app/tests/test_main.py
- app/views/clients.py
- app/views/helpers.py
- app/views/memes.py
- app/views/schemas.py
- app/views/shortcuts.py
- app/views/templates.py
- poetry.lock
- pyproject.toml
- requirements.txt
> Switch to Sanic Extensions

- app/config.py
- app/helpers.py
- app/models/template.py
- app/tests/test_docs.py
- app/views/clients.py
- app/views/memes.py
- app/views/shortcuts.py
- app/views/templates.py
> Rename Blueprints and OpenAPI operations 

- app/config.py
- app/tests/test_views_images.py
> Enable automatic CORS options

- app/tests/test_views_shortcuts.py
- poetry.lock
- pyproject.toml
- requirements.txt
> Upgrade Sanic to 22.3

- app/tests/test_views_shortcuts.py
- poetry.lock
- pyproject.toml
- requirements.txt
Reverts jacebrowning/memegen#709 because it resulted in a bunch of timeouts on production.
> Revert "Upgrade Sanic to 22.3"

- Containerfile
Error: Files owned ny root, memegen user cannot write.
> Fix permission issues

- app/helpers.py
- app/models/template.py
- app/settings.py
- app/utils/images.py
- app/views/helpers.py
- app/views/shortcuts.py
This updated https://github.com/jacebrowning/memegen/pull/775 to add a second setting for the default animated extension. cc @Helvio88
> Make the default animated extension configurable

- .vscode/settings.json
- app/settings.py
- app/tests/conftest.py
- app/utils/images.py
> Remove APNG support

- app/tests/test_utils_text.py
- app/utils/text.py
> Handle short flags in escape characters

- app/models/template.py
- app/views/helpers.py
> Support customizing default templates

- app/models/template.py
> Preserve text and overlay when customizing templates

- Containerfile
> Fix dependency installation in the container

- app/utils/meta.py
- docs/clients.md
> Update example watermark image
